[versions]
kotlin = "2.4.0"
slf4j = "2.0.17"
logback = "1.5.18"
junit = "5.13.4"
junitPlatform = "1.13.4"
assertj = "3.27.3"
awaitility = "4.3.0"
hikari = "6.3.0"
h2 = "2.3.232"
maven = "3.9.16"
mavenResolver = "1.9.27"
gson = "2.13.2"
jdt = "3.46.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
maven-resolver-provider = { module = "org.apache.maven:maven-resolver-provider", version.ref = "maven" }
maven-model-builder = { module = "org.apache.maven:maven-model-builder", version.ref = "maven" }
maven-resolver-supplier = { module = "org.apache.maven.resolver:maven-resolver-supplier", version.ref = "mavenResolver" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jdt-core = { module = "org.eclipse.jdt:org.eclipse.jdt.core", version.ref = "jdt" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
