#!/usr/bin/env node
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { stringify } from "yaml";
import { run } from "../exec.js";
import { packagedLanguageServer, prefetchEnvironment, serenaPrefetchFixtures } from "./serena.js";

export interface PrefetchOptions {
  home: string;
  languages?: string[];
  serenaBin?: string;
}

export async function prefetchSerena(options: PrefetchOptions): Promise<void> {
  const fixtures = serenaPrefetchFixtures();
  const requested = options.languages?.length ? new Set(options.languages) : new Set(fixtures.map((fixture) => fixture.language));
  const selected = fixtures.filter((fixture) => requested.has(fixture.language));
  const missing = [...requested].filter((language) => !fixtures.some((fixture) => fixture.language === language));
  if (missing.length) throw new Error(`unsupported prefetch fixtures: ${missing.join(", ")}`);
  await mkdir(options.home, { recursive: true });
  const configPath = join(options.home, "serena_config.yml");
  const config = {
    language_backend: "LSP",
    web_dashboard: false,
    web_dashboard_open_on_launch: false,
    web_dashboard_interface: "browser",
    gui_log_window: false,
    token_count_estimator: "CHAR_COUNT",
    // Runtime project.yml is generated by Leveret; checkout-owned .serena is evaluation input, never configuration.
    trusted_project_path_patterns: ["**"],
    projects: [],
  };
  await writeFile(configPath, stringify(config));
  const root = await mkdtemp(join(tmpdir(), "leveret-serena-prefetch-"));
  const env = prefetchEnvironment({ ...process.env, SERENA_HOME: options.home });
  const lsPaths: Record<string, string> = {};
  try {
    for (const fixture of selected) {
      const project = join(root, fixture.language);
      for (const file of fixture.files) {
        const path = join(project, file.path);
        await mkdir(dirname(path), { recursive: true });
        await writeFile(path, file.content);
      }
      const result = await run(
        options.serenaBin ?? "serena",
        [
          "project",
          "create",
          project,
          "--name",
          `leveret-prefetch-${fixture.language}`,
          "--ls",
          fixture.language,
          "--index",
          "--log-level",
          "WARNING",
          "--timeout",
          "60",
        ],
        project,
        { timeoutMs: 15 * 60_000, env, maxBuffer: 8 * 1024 * 1024 },
      );
      if (result.code !== 0) {
        throw new Error(`Serena ${fixture.language} prefetch rc=${result.code}: ${result.stderr.slice(0, 1000)}`);
      }
      const packaged = await packagedLanguageServer(options.home, fixture.language);
      if (!packaged) throw new Error(`Serena ${fixture.language} did not stage a self-contained language server`);
      lsPaths[fixture.language] = packaged;
    }
    // Fixture registrations are build-time scaffolding, not runtime projects.
    await writeFile(configPath, stringify(config));
    await writeFile(
      join(options.home, "leveret-lsp-manifest.json"),
      `${JSON.stringify({ languages: selected.map((fixture) => fixture.language), ls_paths: lsPaths, generated_at: new Date().toISOString() }, null, 2)}\n`,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

function cli(argv: string[]): PrefetchOptions {
  let home = process.env.SERENA_HOME;
  let serenaBin = process.env.LEVERET_SERENA_BIN;
  const languages: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    const value = () => (arg.includes("=") ? arg.split("=").slice(1).join("=") : argv[++i]!);
    if (arg === "--home" || arg.startsWith("--home=")) home = value();
    else if (arg === "--serena-bin" || arg.startsWith("--serena-bin=")) serenaBin = value();
    else if (arg === "--language" || arg.startsWith("--language=")) languages.push(value());
    else throw new Error(`unknown prefetch argument: ${arg}`);
  }
  if (!home) throw new Error("--home or SERENA_HOME is required");
  return { home, serenaBin, languages };
}

if (process.argv[1]?.endsWith("prefetch-serena.js")) {
  prefetchSerena(cli(process.argv.slice(2))).catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
